spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name:microservicecloud-config-han-dev
---
spring:
  profiles: test
  application:
    name:name:microservicecloud-config-han-test