spring: 
  profiles: 
    active: 
    - dev
---
server: 
  port: 9012

spring:
  profiles: dev
  application: 
    name: microservicecloud-config-eureka-client

eureka: 
  client: 
    register-with-eureka: false
    fetch-registry: false 
    service-url: 
      defaultZone: http://localhost:9102/eureka/

---
server: 
  port: 9012

spring:
  profiles: test
  application: 
    name: microservicecloud-config-eureka-client
  
eureka: 
  client: 
    register-with-eureka: false
    fetch-registry: false 
    service-url: 
      defaultZone: http://localhost:9102/eureka/
